// <auto-generated />
namespace Sang5_01_07.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class connectionIdentitytoReservations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(connectionIdentitytoReservations));
        
        string IMigrationMetadata.Id
        {
            get { return "202107010352030_connectionIdentitytoReservations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
